// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

// import for all the units
// This was kept seperate for some reason so I'm just leaving it like this
import static edu.wpi.first.units.Units.*;

// pheonix6 imports
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;

// wpilib imports
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine.Direction;
import frc.robot.command.IntakeCommands.lowerLift;
import frc.robot.command.IntakeCommands.startRollers;
import frc.robot.command.IntakeCommands.stopRollers;
// Autogenerated swerve imports
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;

// our subsystem imports
import frc.robot.subsystems.Agitator;
import frc.robot.subsystems.Hood;
import frc.robot.subsystems.IntakeLift;
import frc.robot.subsystems.IntakeRoller;
import frc.robot.subsystems.Shooter;

public class RobotContainer {

    // Set up instance of the network table so we can connect to it
    NetworkTableInstance inst = NetworkTableInstance.getDefault();
    NetworkTable table = inst.getTable("datatable");

    // Speed/turning speed stuff for swerve
    // this is still voltage (angry) but I'm not gonna fix it yet
    private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

    /* Setting up bindings for necessary control of the swerve drive platform */
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(MaxSpeed * 0.1).withRotationalDeadband(MaxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
    private final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();

    // Ethan here - not actually sure how the telemetry stuff works so I am not touching this
    private final Telemetry logger = new Telemetry(MaxSpeed);

    // Leaving this as reference in case we go back to an Xbox controller
    //private final CommandXboxController joystick = new CommandXboxController(0);

    // Define joysticks
    // Please give these better names, like "mainDriverJoystick1" and "codriverJoystick1" or something
    private final Joystick joystickLeft1 = new Joystick(0);
    private final Joystick joystickLeft2 = new Joystick(1);
    private final Joystick joystickRight1 = new Joystick(2);
    private final Joystick joystickRight2 = new Joystick(3);

    // Set up button controls
    // I don't love this setup, it feels like there should be a better way but I am just gonna leave it

    // Swerve buttons
    private final JoystickButton joystickLeft1Button4 = new JoystickButton(joystickLeft1, 4);
    private final JoystickButton joystickLeft1Button3 = new JoystickButton(joystickLeft1, 3);
    private final JoystickButton joystickLeft1Button1 = new JoystickButton(joystickLeft1, 1);

    // Shooter buttons
    private final JoystickButton joystickLeft2Button6 = new JoystickButton(joystickLeft2, 6);
    private final JoystickButton joystickLeft2Button4 = new JoystickButton(joystickLeft2, 4);

    // Subsystem instance declaration
    private final Agitator s_Agitator = new Agitator(); // Not implemented yet

    private final Hood s_Hood = new Hood(); // Not implemented yet

    private final IntakeLift s_IntakeLift = new IntakeLift(new TalonFX(Constants.IntakeConstants.rollerMotorPort));
    private final IntakeRoller s_IntakeRoller = new IntakeRoller(new TalonFX(Constants.IntakeConstants.liftMotorPort), inst.getDoubleTopic("RollerSpeed"));

    private final Shooter s_Shooter = new Shooter(new TalonFX(Constants.ShooterConstants.leaderShooterMotorPort), new TalonFX(Constants.ShooterConstants.followerShooterMotor1Port), inst.getDoubleTopic("RPS"));

    // Swerve instance declaration
    public final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

    public RobotContainer() {
        // Set up which buttons do what
        configureBindings();
    }

    private void configureBindings() {
        // Note that X is defined as forward according to WPILib convention,
        // and Y is defined as to the left according to WPILib convention.
        drivetrain.setDefaultCommand(
            // Drivetrain will execute this command periodically
            drivetrain.applyRequest(() ->
                drive.withVelocityX(joystickLeft1.getY() * MaxSpeed) // Drive forward with negative Y (forward)
                    .withVelocityY(joystickLeft1.getX() * MaxSpeed) // Drive left with negative X (left)
                    .withRotationalRate(joystickLeft2.getX() * MaxAngularRate) // Drive counterclockwise with negative X (left)
            )
        );

        // Idle while the robot is disabled. This ensures the configured
        // neutral mode is applied to the drive motors while disabled.
        final var idle = new SwerveRequest.Idle();
        RobotModeTriggers.disabled().whileTrue(
            drivetrain.applyRequest(() -> idle).ignoringDisable(true)
        );

        joystickLeft1Button4.whileTrue(drivetrain.applyRequest(() -> brake));

        /*
        // Ethan here,
        // I have no idea why all of this is here, cause it all references the Xbox controller
        // which we are not using, so this code shouldn't really be apart of this project.
        // I am, however, terrified that this code actually DOES do something, so I am just commenting
        // it away instead of deleting it.

        joystickLeft1Button3.whileTrue(drivetrain.applyRequest(() ->
            point.withModuleDirection(new Rotation2d(-joystick.getLeftY(), -joystick.getLeftX()))
        ));

        // Run SysId routines when holding back/start and X/Y.
        // Note that each routine should be run exactly once in a single log.
        joystick.back().and(joystick.y()).whileTrue(drivetrain.sysIdDynamic(Direction.kForward));
        joystick.back().and(joystick.x()).whileTrue(drivetrain.sysIdDynamic(Direction.kReverse));
        joystick.start().and(joystick.y()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kForward));
        joystick.start().and(joystick.x()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kReverse));
        */

        // Reset the field-centric heading on left bumper press.
        joystickLeft1Button1.onTrue(drivetrain.runOnce(drivetrain::seedFieldCentric));

        drivetrain.registerTelemetry(logger::telemeterize);

        // SHOOTER CONTROLS
        // Turn shooter on/off
        //joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_Shooter.setMotorSpeedRPM(10)));
        //joystickLeft2Button4.onTrue(Commands.runOnce(() -> s_Shooter.stopMotors()));

        // INTAKE CONTROLS
        // Put intake out and start it
        // something kind of like
        joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_IntakeRoller.spinRoller()));
        joystickLeft2Button4.onTrue(Commands.runOnce(() -> s_IntakeRoller.stopRoller()));

    }

    public Command getAutonomousCommand() {
        // Simple drive forward auton
        final var idle = new SwerveRequest.Idle();
        return Commands.sequence(
            // Reset our field centric heading to match the robot
            // facing away from our alliance station wall (0 deg).
            drivetrain.runOnce(() -> drivetrain.seedFieldCentric(Rotation2d.kZero)),
            // Then slowly drive forward (away from us) for 5 seconds.
            drivetrain.applyRequest(() ->
                drive.withVelocityX(0.5)
                    .withVelocityY(0)
                    .withRotationalRate(0)
            )
            .withTimeout(5.0),
            // Finally idle for the rest of auton
            drivetrain.applyRequest(() -> idle)
        );
    }
}