// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

// import for all the units
// This was kept seperate for some reason so I'm just leaving it like this
import static edu.wpi.first.units.Units.*;

// pheonix6 imports

import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.Pigeon2;

import edu.wpi.first.cameraserver.CameraServer;
import edu.wpi.first.cscore.CvSink;
import edu.wpi.first.cscore.CvSource;
import edu.wpi.first.cscore.MjpegServer;
import edu.wpi.first.cscore.UsbCamera;
// wpilib imports
// import com.pathplanner.lib.auto.NamedCommands;
// import com.pathplanner.lib.commands.PathPlannerAuto;

import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.RawTopic;
import edu.wpi.first.util.PixelFormat;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PS4Controller;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine.Direction;
import frc.robot.command.IntakeCommands.lowerLift;
import frc.robot.command.IntakeCommands.raiseLift;
import frc.robot.command.IntakeCommands.raiseLiftMiddle;
import frc.robot.command.IntakeCommands.startRollers;
import frc.robot.command.IntakeCommands.stopRollers;
// Autogenerated swerve imports

import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.FieldMap;
// our subsystem imports
import frc.robot.subsystems.Agitator;
import frc.robot.subsystems.Hood;
import frc.robot.subsystems.HubTracker;
import frc.robot.subsystems.Indexer;
import frc.robot.subsystems.IntakeLift;
import frc.robot.subsystems.IntakeRoller;
import frc.robot.subsystems.LedControl;
import frc.robot.subsystems.MatchTimer;
import frc.robot.subsystems.PoseEst;
import frc.robot.subsystems.Shooter;
import frc.robot.subsystems.ZoneTracking;

public class RobotContainer {


    private final SendableChooser<String> autos = new SendableChooser<>();

    // Set up instance of the network table so we can connect to it
    NetworkTableInstance inst = NetworkTableInstance.getDefault();
    NetworkTable table = inst.getTable("datatable");

    // Speed/turning speed stuff for swerve
    // this is still voltage (angry) but I'm not gonna fix it yet
    private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

    /* Setting up bindings for necessary control of the swerve drive platform */
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(MaxSpeed * 0.1).withRotationalDeadband(MaxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
    private final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();

    // Ethan here - not actually sure how the telemetry stuff works so I am not touching this
    private final Telemetry logger = new Telemetry(MaxSpeed);

    // Define joysticks
    // Please give these better names, like "mainDriverJoystick1" and "codriverJoystick1" or something
    private final Joystick joystickLeft1 = new Joystick(0);
    private final Joystick joystickLeft2 = new Joystick(1);
    private final Joystick joystickRight1 = new Joystick(2);
    private final Joystick joystickRight2 = new Joystick(3);

    // Set up button controls
    // I don't love this setup, it feels like there should be a better way but I am just gonna leave it

    // Swerve Buttons
    private final JoystickButton joystickLeft1Button5 = new JoystickButton(joystickLeft1, 4);
    private final JoystickButton joystickLeft1Button3 = new JoystickButton(joystickLeft1, 3);
    private final JoystickButton joystickLeft1Button1 = new JoystickButton(joystickLeft1, 1);

    // Shooter Buttons
    private final JoystickButton joystickLeft2Button6 = new JoystickButton(joystickLeft2, 6);
    private final JoystickButton joystickLeft2Button4 = new JoystickButton(joystickLeft2, 4);

    // Hood Control Buttons
    private final JoystickButton joystickLeft1Button6 = new JoystickButton(joystickLeft1, 6);
    private final JoystickButton joystickRight2Button10 = new JoystickButton(joystickRight2, 10);
    private final JoystickButton joystickLeft1Button4 = new JoystickButton(joystickLeft1, 4);
    private final JoystickButton joystickLeft2button2 = new JoystickButton(joystickLeft2, 2);
 
    // Indexer Control Buttons
    private final JoystickButton joystickLeft2Button5 = new JoystickButton(joystickLeft2, 5);
    private final JoystickButton joystickLeft2Button3 = new JoystickButton(joystickLeft2, 3);
    private final JoystickButton joystickLeft2Button11 = new JoystickButton(joystickLeft2,11 );

    //Intake Controls
    private final JoystickButton joystickright1Button6 = new JoystickButton(joystickRight1, 6);
    private final JoystickButton joystickright1Button4 = new JoystickButton(joystickRight1, 4);

    private final JoystickButton joystickright2Button3 = new JoystickButton(joystickRight2,3);
    private final JoystickButton joystickRight1Button7 = new JoystickButton(joystickRight1, 7);
    private final JoystickButton joystickRight1Button8 = new JoystickButton(joystickRight1, 8);
    private final JoystickButton joystickRight1Button9 = new JoystickButton(joystickRight1, 9);
    private final JoystickButton joystickRight1Button10 = new JoystickButton(joystickRight1, 10);
    private final JoystickButton joystickRight1Button12 = new JoystickButton(joystickRight1, 12);
    private final JoystickButton joystickRight1Button11 = new JoystickButton(joystickRight1, 11);

    private final JoystickButton joystickLeft2Button1 = new JoystickButton(joystickLeft2, 1);
    private final JoystickButton joystickRight2Button1 = new JoystickButton(joystickRight2, 1);
    private final JoystickButton joystickRight2Button2 = new JoystickButton(joystickRight2, 2);
    
    // Swerve instance declaration
    public final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();
    public final Pigeon2 gyro = new Pigeon2(Constants.SensorConsants.pigeonPort);

    // Subsystem instance declaration
    private final Agitator s_Agitator = new Agitator(); // Not implemented yet

    private final Hood s_Hood = new Hood(new TalonFX(Constants.HoodConstants.hoodMotorPort), inst.getDoubleTopic("HoodSpeed"), new CANcoder(Constants.SensorConsants.hoodEncoderPort), inst.getDoubleTopic("HoodEncoder"));
    
    private final Indexer s_Indexer = new Indexer(new TalonFX(Constants.IndexerConstants.indexerMotorPort), inst.getDoubleTopic("make2"));
        
    private final IntakeLift s_IntakeLift = new IntakeLift(new TalonFX(Constants.IntakeConstants.liftMotorPort), new CANcoder(Constants.SensorConsants.IntakeLiftEncoderPort), inst.getDoubleTopic("LiftPosition"));
    private final IntakeRoller s_IntakeRoller = new IntakeRoller(new TalonFX(Constants.IntakeConstants.rollerMotorPort), inst.getDoubleTopic("RollerSpeed"), inst.getDoubleTopic("RollerKP"), inst.getDoubleTopic("RollerKV"));

    private final Shooter s_Shooter = new Shooter(new TalonFX(Constants.ShooterConstants.leaderShooterMotorPort), new TalonFX(Constants.ShooterConstants.followerShooterMotor1Port),new TalonFX(Constants.ShooterConstants.followerShooterMotor2Port),new TalonFX(Constants.ShooterConstants.followerShooterMotor3Port), inst.getDoubleTopic("ShooterSpeed"), inst.getDoubleTopic("ShooterKP"), inst.getDoubleTopic("ShooterKV"));

    private final PoseEst s_PoseEst = new PoseEst(drivetrain, gyro, inst.getDoubleTopic("RobotDistance"), inst.getDoubleTopic("RobotX"), inst.getDoubleTopic("RobotY"));

    private final MatchTimer s_MatchTimer = new MatchTimer();

    private final HubTracker s_HubTracker = new HubTracker();

    private final LedControl s_LedControl = new LedControl(Constants.LedConstants.ledPort, Constants.LedConstants.ledLength);

    private final ZoneTracking s_ZoneTracking = new ZoneTracking(drivetrain, s_LedControl);

    private final FieldMap s_FieldMap = new FieldMap(drivetrain);

    public RobotContainer() {
        // Set up which buttons do what
        configureBindings();

        autos.addOption("shoot", "New Auto");

        SmartDashboard.putData("Auto Selection", autos);

        // NamedCommands.registerCommand("Shoot", Commands.runOnce(()-> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.shooterSpeed)));
        // NamedCommands.registerCommand("Indexer", Commands.runOnce(()-> s_Indexer.setMotorSpeedRPM(-35)));

    }

    private void configureBindings() {
        // Note that X is defined as forward according to WPILib convention,
        // and Y is defined as to the left according to WPILib convention.
        drivetrain.setDefaultCommand(
            // Drivetrain will execute this command periodically
            drivetrain.applyRequest(() ->
                drive.withVelocityX(-joystickLeft1.getY() * MaxSpeed) // Drive forward with negative Y (forward)
                    .withVelocityY(-joystickLeft1.getX() * MaxSpeed) // Drive left with negative X (left)
                    .withRotationalRate(-joystickLeft2.getX() * MaxAngularRate) // Drive counterclockwise with negative X (left)
            )
        );

        /*
         * 
        Not actually this but something close
        drivetrain.setDefaultCommand(
            // Drivetrain will execute this command periodically
            drivetrain.applyRequest(() -> new SwerveRequest.FieldCentricFacingAngle().withTargetDirection(PoseEst.something()).withVelocityX(5).withVelocityY(5))
        );
        */
        // Idle while the robot is disabled. This ensures the configured
        // neutral mode is applied to the drive motors while disabled.
        final var idle = new SwerveRequest.Idle();
        RobotModeTriggers.disabled().whileTrue(
            drivetrain.applyRequest(() -> idle).ignoringDisable(true)
        );

        joystickLeft1Button5.whileTrue(drivetrain.applyRequest(() -> brake));

        /*
        // Ethan here,
        // I have no idea why all of this is here, cause it all references the Xbox controller
        // which we are not using, so this code shouldn't really be apart of this project.
        // I am, however, terrified that this code actually DOES do something, so I am just commenting
        // it away instead of deleting it.

        joystickLeft1Button3.whileTrue(drivetrain.applyRequest(() ->
            point.withModuleDirection(new Rotation2d(-joystick.getLeftY(), -joystick.getLeftX()))
        ));

        // Run SysId routines when holding back/start and X/Y.
        // Note that each routine should be run exactly once in a single log.
        joystick.back().and(joystick.y()).whileTrue(drivetrain.sysIdDynamic(Direction.kForward));
        joystick.back().and(joystick.x()).whileTrue(drivetrain.sysIdDynamic(Direction.kReverse));
        joystick.start().and(joystick.y()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kForward));
        joystick.start().and(joystick.x()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kReverse));
        */

        // Reset the field-centric heading on left bumper press.
        joystickLeft1Button1.onTrue(drivetrain.runOnce(drivetrain::seedFieldCentric));

        drivetrain.registerTelemetry(logger::telemeterize);

        // ETHAN NOTE HERE:
        // Noticing you guys are experimenting with commands when you let go of a button, totally fine but here is a better way of doing it:
        // https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html#chaining-calls
        // Essentially, you can do button.onTrue(command1).onFalse(command2) and that is the same as button.onTrue(command1); button.onFalse(command2)
        // but it is a little shorter and a little cleaner

        // ALSO:
        // if you are gonna have 2 buttons do the same command (I don't agree but maybe you want to for some reason), do it this way instead:
        // https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html#composing-triggers
        // This means you can do like button1.and(button2).onTrue(command) for BOTH buttons being pressed
        // or button1.or(button2).onTrue(command) for EITHER button being pressed, super easy and again, short and clean

        //PID TUNING CONTROLS
        joystickLeft2Button1.onTrue(Commands.runOnce(()-> s_IntakeRoller.updatePIDValues()));

        // SHOOTER CONTROLS
        // Turn shooter on/off
           // joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.shooterSpeed)));
        //joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_Shooter.spinShooter()));
        //joystickLeft2Button6.onFalse(Commands.runOnce(() -> s_Shooter.stopMotors()));
        
   
        //joystickLeft2Button4.onTrue(Commands.runOnce(() -> s_Shooter.stopMotors()));
        joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.shooterSpeed)).andThen(new WaitCommand(1)).andThen(Commands.runOnce(() -> s_Indexer.setMotorSpeedRPM(50.0))));
        joystickLeft2Button4.onTrue(Commands.runOnce(()-> s_Shooter.stopMotors()).andThen(Commands.runOnce(() -> s_Indexer.stopRoller())));
        // SHOOTER INDEXER SEQUENCE CONTROL
        // joystickLeft2Button6.onTrue(()-> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.shooterSpeed.andThen(new WaitCommand(1)).andThen(() -> s_Indexer.setMotorSpeedRPM(3))));
        // joystickLeft2Button6.onTrue(Commands.sequence(
        //s_Shooter.runOnce(()-> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.shooterSpeed)), new WaitCommand(2), 
        //  s_Indexer.runOnce(()-> s_Indexer.setMotorSpeedRPM(-35))
        // ));
        //  joystickLeft2Button6.onTrue(Commands.sequence(
        // s_Shooter.runOnce(()-> s_Shooter.stopMotors()),  
        //  s_Indexer.runOnce(()-> s_Indexer.stopRoller())
        // ));
        // HOOD CONTROLS
        
        // joystickLeft1Button6.onTrue(Commands.runOnce(() -> s_Hood.setMotorSpeedRPM(6))).onFalse(Commands.runOnce(()-> s_Hood.stopHood()));
        // joystickRight2Button10.onTrue(Commands.runOnce(() -> s_Hood.stopHood()));
        // joystickLeft1Button4.onTrue(Commands.runOnce(() -> s_Hood.setMotorSpeedRPM(-6))).onFalse(Commands.runOnce(() -> s_Hood.stopHood()));
        // // go to position
        // joystickLeft2button2.onTrue(Commands.runOnce(()-> s_Hood.raiseHood()));
        // joystickRight1Button12.onTrue(Commands.runOnce(()-> s_Hood.raiseHood()));
        // joystickRight1Button11.onTrue(Commands.runOnce(()-> s_Hood.passHood()));

        // INDEXER CONTROLS
        // Turn indexer on/off
        joystickLeft2Button5.onTrue(Commands.runOnce(() -> s_Indexer.setMotorSpeedRPM(35))).onFalse(Commands.runOnce(() -> s_Indexer.stopRoller()));
        joystickLeft2Button3.onTrue(Commands.runOnce(() -> s_Indexer.setMotorSpeedRPM(-10)).andThen(Commands.runOnce(()-> s_IntakeRoller.spinRollerReverse()))).onFalse(Commands.runOnce(() -> s_Indexer.stopRoller()).andThen(Commands.runOnce(()-> s_IntakeRoller.stopRoller())));
        
        

        // INTAKE ROLLER CONTROLS
        // Put intake out and start it
        // something kind of like
        joystickright2Button3.onTrue(new startRollers(s_IntakeRoller));
        joystickright2Button3.onFalse(new stopRollers(s_IntakeRoller));
        //button.onTrue(new lowerLift().andThen(new startRollers()));
        //INTAKE LIFT
        joystickRight2Button1.whileTrue(Commands.runOnce(() -> s_IntakeLift.setMotorSpeedRPM(24))).onFalse(Commands.runOnce(()-> s_IntakeLift.stopLift()));
        joystickRight2Button2.whileTrue(Commands.runOnce(() -> s_IntakeLift.setMotorSpeedRPM(-24))).onFalse(Commands.runOnce(() -> s_IntakeLift.stopLift()));


        joystickRight1Button7.onTrue(new stopRollers(s_IntakeRoller).andThen(new raiseLift(s_IntakeLift)));
        joystickRight1Button8.onTrue(new lowerLift(s_IntakeLift).andThen(new startRollers(s_IntakeRoller)));
        joystickRight1Button9.onTrue(new raiseLiftMiddle(s_IntakeLift).andThen(new startRollers(s_IntakeRoller)));
        joystickRight1Button10.onTrue(Commands.runOnce(() -> s_IntakeLift.stopLift()));

        //joystickRight1Button8.onTrue(Commands.runOnce(() -> s_IntakeLift.raiseLift()));
        //joystickRight1Button12.onTrue(Commands.runOnce(() -> s_IntakeLift.lowerLift()).andThen());

    }

    public Command getAutonomousCommand() {
        // Simple drive forward auton
        // final var idle = new SwerveRequest.Idle();
        return Commands.sequence(
            s_Hood.runOnce(()-> s_Hood.raiseHood()),
            new WaitCommand(1),
            s_Shooter.runOnce(()-> s_Shooter.setMotorSpeedRPM(Constants.ShooterConstants.autonShooterSpeed)),
            new WaitCommand(1),
            s_Indexer.runOnce(()-> s_Indexer.setMotorSpeedRPM(35)),
            new WaitCommand(5),
            s_Shooter.runOnce(()-> s_Shooter.stopMotors()),
            s_Indexer.runOnce(()-> s_Indexer.stopRoller()),
            s_Indexer.runOnce(() -> s_Indexer.stopRoller())
            // // Reset our field centric heading to match the robot
            // // facing away from our alliance station wall (0 deg).
            // drivetrain.runOnce(() -> drivetrain.seedFieldCentric(Rotation2d.kZero)),
            // // Then slowly drive forward (away from us) for 5 seconds.
            // drivetrain.applyRequest(() ->
            //     drive.withVelocityX(0.5)
            //         .withVelocityY(0)
            //         .withRotationalRate(0)
            // )
            // .withTimeout(5.0),
            // // Finally idle for the rest of auton
            // drivetrain.applyRequest(() -> idle)
        );
    }

  
}