// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

// import for all the units
// This was kept seperate for some reason so I'm just leaving it like this
import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.hardware.CANcoder;
// pheonix6 imports
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;

// wpilib imports
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine.Direction;
import frc.robot.command.IntakeCommands.lowerLift;
import frc.robot.command.IntakeCommands.raiseLift;
import frc.robot.command.IntakeCommands.startRollers;
import frc.robot.command.IntakeCommands.stopRollers;
// Autogenerated swerve imports
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;

// our subsystem imports
import frc.robot.subsystems.Agitator;
import frc.robot.subsystems.Hood;
import frc.robot.subsystems.Indexer;
import frc.robot.subsystems.IntakeLift;
import frc.robot.subsystems.IntakeRoller;
import frc.robot.subsystems.Shooter;

public class RobotContainer {

    // Set up instance of the network table so we can connect to it
    NetworkTableInstance inst = NetworkTableInstance.getDefault();
    NetworkTable table = inst.getTable("datatable");

    // Speed/turning speed stuff for swerve
    // this is still voltage (angry) but I'm not gonna fix it yet
    private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

    /* Setting up bindings for necessary control of the swerve drive platform */
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(MaxSpeed * 0.1).withRotationalDeadband(MaxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
    private final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();

    // Ethan here - not actually sure how the telemetry stuff works so I am not touching this
    private final Telemetry logger = new Telemetry(MaxSpeed);

    // Define joysticks
    // Please give these better names, like "mainDriverJoystick1" and "codriverJoystick1" or something
    private final Joystick joystickLeft1 = new Joystick(0);
    private final Joystick joystickLeft2 = new Joystick(1);
    private final Joystick joystickRight1 = new Joystick(2);
    private final Joystick joystickRight2 = new Joystick(3);

    // Set up button controls
    // I don't love this setup, it feels like there should be a better way but I am just gonna leave it

    // Swerve Buttons
    private final JoystickButton joystickLeft1Button4 = new JoystickButton(joystickLeft1, 4);
    private final JoystickButton joystickLeft1Button3 = new JoystickButton(joystickLeft1, 3);
    private final JoystickButton joystickLeft1Button1 = new JoystickButton(joystickLeft1, 1);

    // Shooter Buttons
    private final JoystickButton joystickLeft2Button6 = new JoystickButton(joystickLeft2, 6);
    private final JoystickButton joystickLeft2Button4 = new JoystickButton(joystickLeft2, 4);

    // Hood Control Buttons
    private final JoystickButton joystickRight2Button8 = new JoystickButton(joystickRight2, 8);
    private final JoystickButton joystickRight2Button10 = new JoystickButton(joystickRight2, 10);
    private final JoystickButton joystickRight2Button12 = new JoystickButton(joystickRight2, 12);

    // Indexer Contrl Buttons
    private final JoystickButton joystickLeft2Button5 = new JoystickButton(joystickLeft2, 5);
    private final JoystickButton joystickLeft2Button3 = new JoystickButton(joystickLeft2, 3);
    private final JoystickButton joystickLeft2Button11 = new JoystickButton(joystickLeft2,11 );

    // Subsystem instance declaration
    private final Agitator s_Agitator = new Agitator(); // Not implemented yet

    private final Hood s_Hood = new Hood(new TalonFX(Constants.HoodConstants.hoodMotorPort), inst.getDoubleTopic("HoodSpeed"), new CANcoder(Constants.SensorConsants.hoodEncoderPort), inst.getDoubleTopic("HoodEncoder"));
    
    private final Indexer s_Indexer = new Indexer(new TalonFX(Constants.IndexerConstants.indexerMotorPort), inst.getDoubleTopic("make2"));
        
    private final IntakeLift s_IntakeLift = new IntakeLift(new TalonFX(Constants.IntakeConstants.liftMotorPort), new CANcoder(Constants.SensorConsants.IntakeLiftEncoderPort), inst.getDoubleTopic("LiftPosition"));
    private final IntakeRoller s_IntakeRoller = new IntakeRoller(new TalonFX(Constants.IntakeConstants.rollerMotorPort), inst.getDoubleTopic("RollerSpeed"));

    private final Shooter s_Shooter = new Shooter(new TalonFX(Constants.ShooterConstants.leaderShooterMotorPort), new TalonFX(Constants.ShooterConstants.followerShooterMotor1Port),new TalonFX(Constants.ShooterConstants.followerShooterMotor2Port),new TalonFX(Constants.ShooterConstants.followerShooterMotor3Port), inst.getDoubleTopic("RPS"));

    // Swerve instance declaration
    public final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

    public RobotContainer() {
        // Set up which buttons do what
        configureBindings();
    }

    private void configureBindings() {
        // Note that X is defined as forward according to WPILib convention,
        // and Y is defined as to the left according to WPILib convention.
        drivetrain.setDefaultCommand(
            // Drivetrain will execute this command periodically
            drivetrain.applyRequest(() ->
                drive.withVelocityX(joystickLeft1.getY() * MaxSpeed) // Drive forward with negative Y (forward)
                    .withVelocityY(joystickLeft1.getX() * MaxSpeed) // Drive left with negative X (left)
                    .withRotationalRate(-joystickLeft2.getX() * MaxAngularRate) // Drive counterclockwise with negative X (left)
            )
        );

        // Idle while the robot is disabled. This ensures the configured
        // neutral mode is applied to the drive motors while disabled.
        final var idle = new SwerveRequest.Idle();
        RobotModeTriggers.disabled().whileTrue(
            drivetrain.applyRequest(() -> idle).ignoringDisable(true)
        );

        joystickLeft1Button4.whileTrue(drivetrain.applyRequest(() -> brake));

        /*
        // Ethan here,
        // I have no idea why all of this is here, cause it all references the Xbox controller
        // which we are not using, so this code shouldn't really be apart of this project.
        // I am, however, terrified that this code actually DOES do something, so I am just commenting
        // it away instead of deleting it.

        joystickLeft1Button3.whileTrue(drivetrain.applyRequest(() ->
            point.withModuleDirection(new Rotation2d(-joystick.getLeftY(), -joystick.getLeftX()))
        ));

        // Run SysId routines when holding back/start and X/Y.
        // Note that each routine should be run exactly once in a single log.
        joystick.back().and(joystick.y()).whileTrue(drivetrain.sysIdDynamic(Direction.kForward));
        joystick.back().and(joystick.x()).whileTrue(drivetrain.sysIdDynamic(Direction.kReverse));
        joystick.start().and(joystick.y()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kForward));
        joystick.start().and(joystick.x()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kReverse));
        */

        // Reset the field-centric heading on left bumper press.
        joystickLeft1Button1.onTrue(drivetrain.runOnce(drivetrain::seedFieldCentric));

        drivetrain.registerTelemetry(logger::telemeterize);

        // ETHAN NOTE HERE:
        // Noticing you guys are experimenting with commands when you let go of a button, totally fine but here is a better way of doing it:
        // https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html#chaining-calls
        // Essentially, you can do button.onTrue(command1).onFalse(command2) and that is the same as button.onTrue(command1); button.onFalse(command2)
        // but it is a little shorter and a little cleaner

        // ALSO:
        // if you are gonna have 2 buttons do the same command (I don't agree but maybe you want to for some reason), do it this way instead:
        // https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html#composing-triggers
        // This means you can do like button1.and(button2).onTrue(command) for BOTH buttons being pressed
        // or button1.or(button2).onTrue(command) for EITHER button being pressed, super easy and again, short and clean

        // SHOOTER CONTROLS
        // Turn shooter on/off
        joystickLeft2Button6.onTrue(Commands.runOnce(() -> s_Shooter.setMotorSpeedRPM(-75)));
        //joystickLeft2Button6.onFalse(Commands.runOnce(() -> s_Shooter.stopMotors()));
        joystickLeft2Button4.onTrue(Commands.runOnce(() -> s_Shooter.stopMotors()));


        // HOOD CONTROLS
        joystickRight2Button8.onTrue(Commands.runOnce(() -> s_Hood.setMotorSpeedRPM(3)));
        joystickRight2Button8.onFalse(Commands.runOnce(() -> s_Hood.stopHood()));
        joystickRight2Button10.onTrue(Commands.runOnce(() -> s_Hood.stopHood()));
        joystickRight2Button12.onTrue(Commands.runOnce(() -> s_Hood.setMotorSpeedRPM(-3)));
        joystickRight2Button12.onFalse(Commands.runOnce(() -> s_Hood.stopHood()));
        
        // INDEXER CONTROLS
        // Turn indexer on/off
        joystickLeft2Button5.onTrue(Commands.runOnce(() -> s_Indexer.setMotorSpeedRPM(-50)));
        joystickLeft2Button3.onTrue(Commands.runOnce(() -> s_Indexer.setMotorSpeedRPM(10)));
        joystickLeft2Button5.onFalse(Commands.runOnce(() -> s_Indexer.stopRoller()));
        joystickLeft2Button3.onFalse(Commands.runOnce(() -> s_Indexer.stopRoller()));

        // INTAKE ROLLER CONTROLS
        // Put intake out and start it
        // something kind of like
        //joystickLeft2Button5.onTrue(new startRollers(s_IntakeRoller));
        //joystickLeft2Button3.onTrue(new stopRollers(s_IntakeRoller));
        //button.onTrue(new lowerLift().andThen(new startRollers()));
        //INTAKE LIFT
        //joystickLeft2Button5.onTrue(new raiseLift(s_IntakeLift));
        //joystickLeft2Button3.onTrue(new lowerLift(s_IntakeLift));
        //joystickLeft2Button5.onTrue(Commands.runOnce(() -> s_IntakeLift.raiseLift()));
        //joystickLeft2Button3.onTrue(Commands.runOnce(() -> s_IntakeLift.lowerLift()));

    }

    public Command getAutonomousCommand() {
        // Simple drive forward auton
        final var idle = new SwerveRequest.Idle();
        return Commands.sequence(
            // Reset our field centric heading to match the robot
            // facing away from our alliance station wall (0 deg).
            drivetrain.runOnce(() -> drivetrain.seedFieldCentric(Rotation2d.kZero)),
            // Then slowly drive forward (away from us) for 5 seconds.
            drivetrain.applyRequest(() ->
                drive.withVelocityX(0.5)
                    .withVelocityY(0)
                    .withRotationalRate(0)
            )
            .withTimeout(5.0),
            // Finally idle for the rest of auton
            drivetrain.applyRequest(() -> idle)
        );
    }
}